# Nome da pipeline
name: Cypress Pipeline

# Em que evento a pipeline será executada
# Neste caso, a pipeline será executado quando houver um pull request para a branch master
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# Definição dos jobs
# Cada job é executado em um ambiente separado e pode ter suas próprias etapas      
jobs:
  # Job para executar o Cypress
  # No ambiente Ubuntu  
  cypress-run:
    runs-on: ubuntu-latest

    # Definição das variáveis de ambiente
    # As variáveis de ambiente são definidas a partir dos secrets do repositório
    env:
     BASE_URL: ${{ secrets.BASE_URL }}
     USER_EMAIL: ${{ secrets.USER_EMAIL }}
     LOCKED_USER: ${{ secrets.LOCKED_USER }}
     PASSWORD_USER: ${{ secrets.PASSWORD_USER }}

    # Definição das etapas do job  
    steps:
      - name: Checkout/Clone do projeto
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Install Cypress binary
        run: npx cypress install --force

      - name: Run Cypress tests
        run: npx cypress run --browser electron

      # Upload do relatório do mocha
      - name: upload relatório
        uses: actions/upload-artifact@v4
        with:
          name: Relatório
          path: cypress/reports
